#!/bin/bash
echo "Checking CDN's IPs VS Server's Firewall IPs"

cdn="$(curl -sL https://www.arvancloud.ir/en/ips.txt)"

fw="$(cat /etc/iptables/rules.v4 | awk '{print $4}' | awk -F '[^0-9]*' '$1' | sed '/127.\(.*\)/d')"

date=$(date +"%a %b %d %I:%M:%S %Y")

# Counters to track changes
ADD_COUNTER=0
REMOVE_COUNTER=0

# Fetch IP addresses from Arvancloud
CDN=()
while IFS= read -r line; do
  CDN+=("$line")
done < <(echo "${cdn}")

# Read IP addresses from Firewall
FIREWALL=()
while IFS= read -r line; do
  FIREWALL+=("$line")
done < <(echo "$fw")

# Compare IP addresses between CDN and Firewall
for cdn in "${CDN[@]}"; do
  # Check if the IP exists in Firewall
  FOUND=false
  for firewall in "${FIREWALL[@]}"; do
    if [ "${cdn}" == "${firewall}" ]; then
      FOUND=true
      break
    fi
  done

  if ! "$FOUND"; then
    curl -k -XPOST -H "Authorization: ApiKey " https://metrics-api.nxbo.ir/cdn-changes/_doc -H 'Content-Type: application/json' \ 
    -d "{\"Date\": \"${date}\", \"Hostname\": \"${HOSTNAME}\", \"CDN-Status\": \"New IP Added To CDN\ ${cdn}", \"Server-Status\": \"New IP Added To Firewall\ ${cdn}"} "
    sed -i "/.\(.*\)DROP$/i -A INPUT -s ${cdn} -p tcp -m tcp --dport 443 -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT" /etc/iptables/rules.v4
    ADD_COUNTER=$((ADD_COUNTER+1))
  fi
done

for FW in "${FIREWALL[@]}"; do
  FOUND=false
  for ip in "${CDN[@]}"; do
    if [ "${FW}" == "${ip}" ]; then
      FOUND=true
      break
    fi
  done

  if ! "$FOUND"; then
    curl -k -XPOST -H "Authorization: ApiKey " https://metrics-api.nxbo.ir/cdn-changes/_doc -H 'Content-Type: application/json' \ 
    -d "{\"Date\": \"${date}\", \"Hostname\": \"${HOSTNAME}\", \"CDN-Status\": \"IP Removed From CDN\ ${FW}", \"Server-Status\": \"IP Removed From Firewall\ ${FW}"} "
    removable_ip=`echo "${FW}" | awk -F "/" '{print $1}'`
    sed -i "/.\(.*\) ${removable_ip}/d" /etc/iptables/rules.v4
    REMOVE_COUNTER=$((REMOVE_COUNTER+1))
  fi
done

# If any changes were made, restart iptables
if [ $ADD_COUNTER -gt 0 ] || [ $REMOVE_COUNTER -gt 0 ]; then

  # echo "Changes detected. Restarting iptables service."
  iptables-restore < /etc/iptables/rules.v4

fi
